[package]
name = "iota-proxy"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
# external dependencies
anyhow.workspace = true
axum.workspace = true
axum-extra.workspace = true
axum-server.workspace = true
bcs.workspace = true
bytes.workspace = true
clap.workspace = true
const-str.workspace = true
fastcrypto.workspace = true
git-version.workspace = true
hex.workspace = true
hyper.workspace = true
itertools.workspace = true
multiaddr.workspace = true
once_cell.workspace = true
prometheus-filtered.workspace = true
prost.workspace = true
protobuf = { version = "3.7.2", features = ["with-bytes"] }
rand.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
snap.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "signal", "sync", "time"] }
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true

# internal dependencies
iota-metrics.workspace = true
iota-sdk.workspace = true
iota-sdk-types.workspace = true
iota-tls.workspace = true
iota-types.workspace = true
telemetry-subscribers.workspace = true

[dev-dependencies]
axum-server.workspace = true
mime = "0.3"
tower.workspace = true

[build-dependencies]
prost-build.workspace = true

[lints]
workspace = true
