// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2024 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::ops::Deref;

use serde::{Deserialize, Serialize};

use crate::{
    attestation::Attestation,
    committee::EpochId,
    crypto::AuthorityStrongQuorumSignInfo,
    message_envelope::{Envelope, TrustedEnvelope, VerifiedEnvelope},
    messages_checkpoint::CheckpointSequenceNumber,
    transaction::{SenderSignedData, TransactionDataAPI},
};

/// CertificateProof is a proof that a transaction certs existed at a given
/// epoch and hence can be executed. There are two types of proofs: one that is
/// proven by inclusion in a checkpoint and one that is proven by quorum
/// signature.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum CertificateProof {
    /// Validity was proven by inclusion in the given checkpoint
    Checkpoint(EpochId, CheckpointSequenceNumber),
    /// Validity was proven by transaction certificate signature
    Certified(AuthorityStrongQuorumSignInfo),
    /// At least f+1 validators have executed this transaction.
    /// In practice, we will always get 2f+1 (effects cert), but theoretically
    /// f+1 is enough to prove that the transaction is valid.
    QuorumExecuted(EpochId),
    /// Transaction generated by the system, for example Clock update
    /// transaction
    SystemTransaction(EpochId),
    /// White flag transaction ordered by consensus. Bypasses pre-consensus
    /// certification. Validity proven by consensus ordering post owned-object
    /// conflict resolution.
    ConsensusOrdered(EpochId),
}

impl CertificateProof {
    pub fn new_from_cert_sig(sig: AuthorityStrongQuorumSignInfo) -> Self {
        Self::Certified(sig)
    }

    pub fn new_from_checkpoint(epoch: EpochId, checkpoint: CheckpointSequenceNumber) -> Self {
        Self::Checkpoint(epoch, checkpoint)
    }

    pub fn new_system(epoch: EpochId) -> Self {
        Self::SystemTransaction(epoch)
    }

    pub fn epoch(&self) -> EpochId {
        match self {
            Self::Checkpoint(epoch, _)
            | Self::QuorumExecuted(epoch)
            | Self::SystemTransaction(epoch)
            | Self::ConsensusOrdered(epoch) => *epoch,
            Self::Certified(sig) => sig.epoch,
        }
    }
}

/// An ExecutableTransaction is a wrapper of a transaction with a
/// CertificateProof that indicates there existed a valid certificate for this
/// transaction, and hence it can be executed locally. This is an abstraction
/// data structure to cover both the case where the transaction is certified or
/// checkpointed when we schedule it for execution.
pub type ExecutableTransaction = Envelope<SenderSignedData, CertificateProof>;
pub type VerifiedExecutableTransaction = VerifiedEnvelope<SenderSignedData, CertificateProof>;
pub type TrustedExecutableTransaction = TrustedEnvelope<SenderSignedData, CertificateProof>;

impl VerifiedExecutableTransaction {
    pub fn certificate_sig(&self) -> Option<&AuthorityStrongQuorumSignInfo> {
        match self.auth_sig() {
            CertificateProof::Certified(sig) => Some(sig),
            _ => None,
        }
    }

    pub fn gas_budget(&self) -> u64 {
        self.data().transaction_data().gas_budget()
    }
}

/// Wraps a [`VerifiedExecutableTransaction`] with its pre-consensus
/// [`Attestation`] (if any). Carrying the full attestation lets downstream code
/// consult both scheduling metadata and attestor identity / observed object
/// versions.
#[derive(Clone, Debug)]
pub struct VerifiedExecutableAttestedTransaction {
    tx: VerifiedExecutableTransaction,
    /// `None` for unattested transactions (e.g., `UserTransactionV1`).
    attestation: Option<Attestation>,
}

impl VerifiedExecutableAttestedTransaction {
    pub fn new(tx: VerifiedExecutableTransaction, attestation: Option<Attestation>) -> Self {
        Self { tx, attestation }
    }

    /// Returns the attached attestation, if any.
    pub fn attestation(&self) -> Option<&Attestation> {
        self.attestation.as_ref()
    }

    /// Returns the attestor's estimated computation cost, or `None` if the
    /// transaction was not attested.
    pub fn attested_computation_cost(&self) -> Option<u64> {
        self.attestation
            .as_ref()
            .map(|a| a.estimated_computation_cost())
    }

    /// Consume the wrapper and return its parts.
    pub fn into_parts(self) -> (VerifiedExecutableTransaction, Option<Attestation>) {
        (self.tx, self.attestation)
    }
}

impl From<VerifiedExecutableTransaction> for VerifiedExecutableAttestedTransaction {
    fn from(tx: VerifiedExecutableTransaction) -> Self {
        Self {
            tx,
            attestation: None,
        }
    }
}

impl Deref for VerifiedExecutableAttestedTransaction {
    type Target = VerifiedExecutableTransaction;

    fn deref(&self) -> &Self::Target {
        &self.tx
    }
}
