[package]
name = "iota-swarm-config"
version.workspace = true
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
# external dependencies
anemo.workspace = true
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
rand.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
tracing.workspace = true

# internal dependencies
iota-common.workspace = true
iota-config.workspace = true
iota-genesis-builder.workspace = true
iota-names.workspace = true
iota-protocol-config.workspace = true
iota-sdk-types.workspace = true
iota-types.workspace = true
prometheus-filtered.workspace = true

[target.'cfg(msim)'.dependencies]
iota-simulator.workspace = true

[dev-dependencies]
# external dependencies
insta.workspace = true
tempfile.workspace = true

# internal dependencies
iota-execution.workspace = true
