#!/usr/bin/env bash
#
# start.sh — bring up the local iota-private-network configured for the
# validator-attestation / sequencer (TotalComputationUnits) stress test.
#
# It sets the protocol-config overrides this test needs, then calls the
# network's own run.sh (forwarding any args). Every knob is an env var, so you
# can change the congestion mode / limits between runs WITHOUT rebuilding the
# Rust code or docker images:
#
#   ./start.sh                                   # 4 validators + faucet, attested, TotalComputationUnits
#   ./start.sh -n 10 faucet                      # args forwarded straight to run.sh
#   MODE=TotalGasBudget ./start.sh               # baseline congestion mode
#   ATTEST=false ./start.sh                      # disable validator attestation
#   PCOOL=false ./start.sh                       # disable white-flag-flow
#   MAX_ACCUMULATED_TXN_COST=2999999 ./start.sh
#   ATTESTOR_SKEW_PERCENT=50 ./start.sh          # W6: poison one attestor to under-report (50% of real cost)
#   ATTESTOR_SKEW_PERCENT=200 ./start.sh         # W7: poison one attestor to over-report (200% of real cost)
#   ATTESTOR_SKEW_PERCENT=50 ATTESTOR_SKEW_VALIDATOR=validator-3 ./start.sh   # choose which validator
#
# run.sh args: [-n NUM_VALIDATORS] [faucet | backup | indexer | indexer-cluster | all ...]
#
set -euo pipefail

# Resolve the repo root from this script's own location so it can be invoked
# from any directory. This script lives at <repo>/stress-attestation-sequencer/.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# iota-private-network tooling inside the monorepo (override with PRIVNET_DIR=...).
PRIVNET_DIR="${PRIVNET_DIR:-$REPO_ROOT/dev-tools/iota-private-network}"

# --- Protocol-config overrides (docker-compose forwards these to every node) --
# Attestation + white-flag-flow ON; congestion mode = TotalComputationUnits.
export IOTA_PROTOCOL_CONFIG_OVERRIDE_ENABLE=1
export IOTA_PROTOCOL_CONFIG_FEATURE_FLAGS_OVERRIDE_ENABLE_WHITE_FLAG_FLOW="${PCOOL:-true}"
export IOTA_PROTOCOL_CONFIG_FEATURE_FLAGS_OVERRIDE_ENABLE_VALIDATOR_ATTESTATION="${ATTEST:-true}"
export IOTA_PROTOCOL_CONFIG_FEATURE_FLAGS_OVERRIDE_PER_OBJECT_CONGESTION_CONTROL_MODE="${MODE:-TotalComputationUnits}"

# Optional numeric limits: only exported when provided, so the protocol
# version's own value stands otherwise (avoids pinning a baseline by accident).
if [[ -n "${MAX_ACCUMULATED_TXN_COST:-}" ]]; then
  export IOTA_PROTOCOL_CONFIG_OVERRIDE_MAX_ACCUMULATED_TXN_COST_PER_OBJECT_IN_MYSTICETI_COMMIT="$MAX_ACCUMULATED_TXN_COST"
fi
if [[ -n "${MAX_CONGESTION_OVERSHOOT:-}" ]]; then
  export IOTA_PROTOCOL_CONFIG_OVERRIDE_MAX_CONGESTION_LIMIT_OVERSHOOT_PER_COMMIT="$MAX_CONGESTION_OVERSHOOT"
fi
if [[ -n "${MAX_DEFERRAL_ROUNDS:-}" ]]; then
  export IOTA_PROTOCOL_CONFIG_OVERRIDE_MAX_DEFERRAL_ROUNDS_FOR_CONGESTION_CONTROL="$MAX_DEFERRAL_ROUNDS"
fi

# --- Sanity checks ------------------------------------------------------------
if [[ ! -d "$PRIVNET_DIR" ]]; then
  echo "ERROR: PRIVNET_DIR not found: $PRIVNET_DIR" >&2
  exit 1
fi
if [[ ! -f "$PRIVNET_DIR/configs/genesis/genesis.blob" ]]; then
  echo "ERROR: network not bootstrapped (missing configs/genesis/genesis.blob)." >&2
  echo "       Bootstrap first, e.g.: (cd '$PRIVNET_DIR' && ./bootstrap.sh -b)" >&2
  exit 1
fi

# --- Per-validator attestor cost skew (W6 under- / W7 over-reporting) ---------
# IOTA_ATTESTOR_COST_SKEW_PERCENT is NOT a protocol-config override: it is a
# plain process env read by the attestor (attest_transaction), so it is not
# network-wide and is not gated by IOTA_PROTOCOL_CONFIG_OVERRIDE_ENABLE. To
# poison a SINGLE validator we write a docker-compose.override.yaml (compose
# auto-merges it and merges each service's `environment` additively on top of
# the shared common-env). Unset => honest: remove any override we generated.
# 100 (or unset) is honest, <100 under-reports (W6), >100 over-reports (W7).
ATTESTOR_SKEW_VALIDATOR="${ATTESTOR_SKEW_VALIDATOR:-validator-1}"
SKEW_OVERRIDE="$PRIVNET_DIR/docker-compose.override.yaml"
SKEW_MARKER="# generated by start.sh (attestor cost skew); safe to delete"
if [[ -n "${ATTESTOR_SKEW_PERCENT:-}" ]]; then
  cat >"$SKEW_OVERRIDE" <<EOF
$SKEW_MARKER
services:
  $ATTESTOR_SKEW_VALIDATOR:
    environment:
      - IOTA_ATTESTOR_COST_SKEW_PERCENT=$ATTESTOR_SKEW_PERCENT
EOF
elif [[ -f "$SKEW_OVERRIDE" ]] && IFS= read -r _first <"$SKEW_OVERRIDE" && [[ "$_first" == "$SKEW_MARKER" ]]; then
  # Remove only an override we generated, never a hand-written one.
  rm -f "$SKEW_OVERRIDE"
fi

# --- Forward to run.sh --------------------------------------------------------
run_args=("$@")
if [[ ${#run_args[@]} -eq 0 ]]; then
  run_args=(faucet)
fi

# Colors (auto-disabled when stdout is not a terminal).
if [[ -t 1 ]]; then
  GREEN=$'\033[0;32m'
  RED=$'\033[0;31m'
  BLUE=$'\033[0;34m'
  YELLOW=$'\033[0;33m'
  CYAN=$'\033[0;36m'
  MAGENTA=$'\033[0;35m'
  RESET=$'\033[0m'
else
  GREEN=''
  RED=''
  BLUE=''
  YELLOW=''
  CYAN=''
  MAGENTA=''
  RESET=''
fi

echo "${BLUE}iota-private-network @ $PRIVNET_DIR${RESET}"
echo "${CYAN}  - enable_white_flag_flow             = $IOTA_PROTOCOL_CONFIG_FEATURE_FLAGS_OVERRIDE_ENABLE_WHITE_FLAG_FLOW${RESET}"
echo "${CYAN}  - enable_validator_attestation       = $IOTA_PROTOCOL_CONFIG_FEATURE_FLAGS_OVERRIDE_ENABLE_VALIDATOR_ATTESTATION${RESET}"
echo "${CYAN}  - per_object_congestion_control_mode = $IOTA_PROTOCOL_CONFIG_FEATURE_FLAGS_OVERRIDE_PER_OBJECT_CONGESTION_CONTROL_MODE${RESET}"
if [[ -n "${ATTESTOR_SKEW_PERCENT:-}" ]]; then
  echo "${MAGENTA}  - attestor cost skew (test-only)     = ${ATTESTOR_SKEW_PERCENT}% on ${ATTESTOR_SKEW_VALIDATOR}${RESET}"
fi
echo "${YELLOW}run.sh ${run_args[*]}${RESET}"
echo

cd "$PRIVNET_DIR"
./run.sh "${run_args[@]}"

# --- Wait for validators and verify they applied the overrides we set ---------
# We only check the protocol-config overrides this script actually exported
# (the 3 flags above, plus any numeric limit you set). The override macro logs
# each applied field as: ProtocolConfig field "<f>" has been overridden with
# the value: <v>  — so we poll each validator's log until those lines match.
READY_TIMEOUT="${READY_TIMEOUT:-120}"

declare -A expected
while IFS='=' read -r _name _value; do
  case "$_name" in
  IOTA_PROTOCOL_CONFIG_OVERRIDE_ENABLE) continue ;; # the gate, not a config field
  IOTA_PROTOCOL_CONFIG_FEATURE_FLAGS_OVERRIDE_*) _field="${_name#IOTA_PROTOCOL_CONFIG_FEATURE_FLAGS_OVERRIDE_}" ;;
  IOTA_PROTOCOL_CONFIG_OVERRIDE_*) _field="${_name#IOTA_PROTOCOL_CONFIG_OVERRIDE_}" ;;
  *) continue ;;
  esac
  expected["${_field,,}"]="$_value"
done < <(env | grep -E '^IOTA_PROTOCOL_CONFIG_(FEATURE_FLAGS_)?OVERRIDE_')

list_validators() { docker compose ps --services 2>/dev/null | grep -E '^validator-[0-9]+$' | sort; }
mismatches() { # $1 = service ; prints "field expected got" for each missing/wrong override
  local svc="$1" logs field want pfx
  logs="$(docker compose logs "$svc" 2>&1)"
  for field in "${!expected[@]}"; do
    want="${expected[$field]}"
    pfx="ProtocolConfig field \"$field\" has been overridden with the value:"
    # The override log prints the value via {:?} (Debug). For Option<T> fields
    # (e.g. max_deferral_rounds_for_congestion_control, the congestion limits)
    # that's "Some(<v>)", not "<v>" — accept both so Option overrides verify.
    grep -qF "$pfx $want" <<<"$logs" || grep -qF "$pfx Some($want)" <<<"$logs" ||
      echo "  [$svc] $field (want '$want')"
  done
}

echo
echo "${YELLOW}Verifying validators applied:${RESET}"
for _f in "${!expected[@]}"; do echo "${CYAN}  - $_f = ${expected[$_f]}${RESET}"; done
ok=false
deadline=$((SECONDS + READY_TIMEOUT))
while ((SECONDS < deadline)); do
  mapfile -t vals < <(list_validators)
  if ((${#vals[@]} > 0)); then
    all_ok=true
    for v in "${vals[@]}"; do
      if [[ -n "$(mismatches "$v")" ]]; then all_ok=false; fi
    done
    if $all_ok; then
      ok=true
      break
    fi
  fi
  sleep 3
done

if ! $ok; then
  echo "${RED}ERROR: validators did not apply the expected overrides within ${READY_TIMEOUT}s:${RESET}" >&2
  for v in $(list_validators); do
    while IFS= read -r _line; do echo "${RED}${_line}${RESET}" >&2; done < <(mismatches "$v")
  done
  echo "Tearing down (docker compose down --remove-orphans)..." >&2
  docker compose down --remove-orphans || true
  exit 1
fi

echo "${GREEN}OK: all validators applied the requested overrides.${RESET}"

# --- Verify the attestor cost skew landed on exactly the chosen validator -----
# Not a protocol-config override, so it is checked separately: read the
# container's configured env via `docker inspect` (reliable even before any
# transaction is attested, unlike grepping for the runtime warn line).
if [[ -n "${ATTESTOR_SKEW_PERCENT:-}" ]]; then
  echo
  echo "${YELLOW}Verifying attestor cost skew on ${ATTESTOR_SKEW_VALIDATOR}...${RESET}"
  _cid="$(docker compose ps -q "$ATTESTOR_SKEW_VALIDATOR" 2>/dev/null || true)"
  if [[ -n "$_cid" ]] && docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' "$_cid" 2>/dev/null |
    grep -qx "IOTA_ATTESTOR_COST_SKEW_PERCENT=${ATTESTOR_SKEW_PERCENT}"; then
    echo "${GREEN}OK: ${ATTESTOR_SKEW_VALIDATOR} carries IOTA_ATTESTOR_COST_SKEW_PERCENT=${ATTESTOR_SKEW_PERCENT} (others honest).${RESET}"
  else
    echo "${RED}ERROR: ${ATTESTOR_SKEW_VALIDATOR} is missing IOTA_ATTESTOR_COST_SKEW_PERCENT=${ATTESTOR_SKEW_PERCENT}.${RESET}" >&2
    echo "       Is ${ATTESTOR_SKEW_VALIDATOR} among the started validators? Check -n / NUM_VALIDATORS." >&2
    exit 1
  fi
fi

# --- Bring up monitoring, now that the network is up ---
# We start ONLY the services these experiments use: prometheus (metrics) + grafana
# (view) + cadvisor/node-exporter (container/host metrics). We deliberately SKIP
# `tempo` (distributed tracing — unused here): it alone publishes 6 host ports
# (3200, 14268, 9095, 4317, 4318, 9411), and cycling it down+up every run is what
# kept leaking an orphaned docker-proxy that `docker compose down` cannot reap,
# leaving a port permanently bound -> "address already in use". Not starting tempo
# removes that failure mode (and the contended ports) entirely.
GRAFANA_DIR="${GRAFANA_DIR:-$REPO_ROOT/dev-tools/grafana-local}"
MON_SERVICES=(prometheus grafana cadvisor node-exporter)
MON_PORTS=(9090 3000 8080 9100) # host ports the above bind (no tempo ports)
# Need root to kill a root-owned orphaned docker-proxy; use sudo when not root.
# `sudo -n` so this can NEVER block on a password prompt (during matrix runs the
# credential is already cached; standalone non-root just falls back to the retry).
if [[ ${EUID:-$(id -u)} -eq 0 ]]; then SUDO=(); else SUDO=(sudo -n); fi

# Guarantee every monitoring host port is FREE before `docker compose up`, so
# "address already in use" cannot recur. `docker compose down` removes containers
# it tracks, but a stray/cross-project container — or an orphaned `docker-proxy`
# left behind when a container is force-killed under load — can keep a host port
# bound. For each port we: (1) force-remove any container publishing it, then
# (2) kill whatever still holds it (the orphan proxy). After this the port is free.
# (Requires `fuser`, from psmisc — present on Ubuntu/Arch; failures are tolerated.)
free_mon_ports() {
  local p c
  for p in "${MON_PORTS[@]}"; do
    c="$(docker ps -aq --filter "publish=$p" 2>/dev/null)"
    [[ -n "$c" ]] && docker rm -f $c >/dev/null 2>&1 || true
    "${SUDO[@]}" fuser -k "$p/tcp" >/dev/null 2>&1 || true
  done
}

if [[ -d "$GRAFANA_DIR" ]]; then
  echo
  echo "${BLUE}grafana-local @ $GRAFANA_DIR (services: ${MON_SERVICES[*]}; tempo skipped)${RESET}"
  _mon_up=""
  for _attempt in 1 2 3 4 5; do
    (cd "$GRAFANA_DIR" && docker compose down --remove-orphans) >/dev/null 2>&1 || true
    free_mon_ports # provably free the ports (kills stray containers + orphan proxies)
    sleep 1
    if (cd "$GRAFANA_DIR" && docker compose up -d "${MON_SERVICES[@]}"); then
      _mon_up=1
      break
    fi
    echo "${YELLOW}Monitoring up failed (attempt ${_attempt}/5); freeing ports + retrying in 5s...${RESET}" >&2
    sleep 5
  done
  if [[ -z "$_mon_up" ]]; then
    echo "${RED}ERROR: monitoring stack failed to start after 5 attempts. Ports still held:${RESET}" >&2
    "${SUDO[@]}" ss -ltnp 2>/dev/null | grep -E ":($(
      IFS='|'
      echo "${MON_PORTS[*]}"
    ))\b" >&2 || true
    echo "${RED}  Last resort to reap orphaned proxies: sudo systemctl restart docker.${RESET}" >&2
    exit 1
  fi
  echo "${GREEN}Monitoring up - [Grafana](http://localhost:3000), [Prometheus](http://localhost:9090)${RESET}"
else
  echo "${YELLOW}WARN: monitoring dir not found, skipping: $GRAFANA_DIR${RESET}" >&2
fi
